/**
 * Copyright (C) 2015 Dato, Inc.
 * All rights reserved.
 *
 * This software may be modified and distributed under the terms
 * of the BSD license. See the LICENSE file for details.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_graphlab_Aggregator */

#ifndef _Included_org_graphlab_Aggregator
#define _Included_org_graphlab_Aggregator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_graphlab_Aggregator
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_graphlab_Aggregator_initNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
