/**
 * Copyright (C) 2015 Dato, Inc.
 * All rights reserved.
 *
 * This software may be modified and distributed under the terms
 * of the BSD license. See the LICENSE file for details.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_graphlab_Updater */

#ifndef _Included_org_graphlab_Updater
#define _Included_org_graphlab_Updater
#ifdef __cplusplus
extern "C" {
#endif
#undef org_graphlab_Updater_IN_EDGES
#define org_graphlab_Updater_IN_EDGES 0L
#undef org_graphlab_Updater_OUT_EDGES
#define org_graphlab_Updater_OUT_EDGES 1L
#undef org_graphlab_Updater_ALL_EDGES
#define org_graphlab_Updater_ALL_EDGES 2L
#undef org_graphlab_Updater_NO_EDGES
#define org_graphlab_Updater_NO_EDGES 3L
#undef org_graphlab_Updater_NULL_CONSISTENCY
#define org_graphlab_Updater_NULL_CONSISTENCY 0L
#undef org_graphlab_Updater_VERTEX_CONSISTENCY
#define org_graphlab_Updater_VERTEX_CONSISTENCY 1L
#undef org_graphlab_Updater_EDGE_CONSISTENCY
#define org_graphlab_Updater_EDGE_CONSISTENCY 2L
#undef org_graphlab_Updater_FULL_CONSISTENCY
#define org_graphlab_Updater_FULL_CONSISTENCY 3L
#undef org_graphlab_Updater_DEFAULT_CONSISTENCY
#define org_graphlab_Updater_DEFAULT_CONSISTENCY 4L
/*
 * Class:     org_graphlab_Updater
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_graphlab_Updater_initNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
