/**
 * Copyright (C) 2016 Turi
 * All rights reserved.
 *
 * This software may be modified and distributed under the terms
 * of the BSD license. See the LICENSE file for details.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_graphlab_Context */

#ifndef _Included_org_graphlab_Context
#define _Included_org_graphlab_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_graphlab_Context
 * Method:    schedule
 * Signature: (JLorg/graphlab/Updater;I)V
 */
JNIEXPORT void JNICALL Java_org_graphlab_Context_schedule
  (JNIEnv *, jobject, jlong, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
