/**
 * Copyright (C) 2016 Turi
 * All rights reserved.
 *
 * This software may be modified and distributed under the terms
 * of the BSD license. See the LICENSE file for details.
 */
#undef event_active
#undef event_active_nolock
#undef event_add
#undef event_assign
#undef event_base_add_virtual
#undef event_base_assert_ok
#undef event_base_del_virtual
#undef event_base_dispatch
#undef event_base_dump_events
#undef event_base_free
#undef event_base_get_deferred_cb_queue
#undef event_base_get_features
#undef event_base_get_method
#undef event_base_gettimeofday_cached
#undef event_base_got_break
#undef event_base_got_exit
#undef event_base_init_common_timeout
#undef event_base_loop
#undef event_base_loopbreak
#undef event_base_loopexit
#undef event_base_new
#undef event_base_new_with_config
#undef event_base_once
#undef event_base_priority_init
#undef event_base_set
#undef event_base_start_iocp
#undef event_base_stop_iocp
#undef event_config_avoid_method
#undef event_config_free
#undef event_config_new
#undef event_config_require_features
#undef event_config_set_flag
#undef event_config_set_num_cpus_hint
#undef event_debug_map_HT_CLEAR
#undef event_debug_map_HT_GROW
#undef _event_debug_map_HT_REP_IS_BAD
#undef _event_debug_mode_on
#undef event_debug_unassign
#undef event_deferred_cb_cancel
#undef event_deferred_cb_init
#undef event_deferred_cb_queue_init
#undef event_deferred_cb_schedule
#undef event_del
#undef event_dispatch
#undef event_enable_debug_mode
#undef event_free
#undef event_get_assignment
#undef event_get_base
#undef event_get_callback
#undef event_get_callback_arg
#undef event_get_events
#undef event_get_fd
#undef event_get_method
#undef event_get_struct_event_size
#undef event_get_supported_methods
#undef event_get_version
#undef event_get_version_number
#undef event_global_current_base_
#undef event_global_setup_locks_
#undef event_init
#undef event_initialized
#undef event_loop
#undef event_loopbreak
#undef event_loopexit
#undef event_mm_calloc_
#undef event_mm_free_
#undef event_mm_malloc_
#undef event_mm_realloc_
#undef event_mm_strdup_
#undef event_new
#undef event_once
#undef event_pending
#undef event_priority_init
#undef event_priority_set
#undef event_reinit
#undef event_set
#undef event_set_mem_functions
#undef evthread_make_base_notifiable
#undef _evthread_cond_fns
#undef _evthread_debug_get_real_lock
#undef evthread_enable_lock_debuging
#undef _evthread_id_fn
#undef _evthread_is_debug_lock_held
#undef _evthread_lock_debugging_enabled
#undef _evthread_lock_fns
#undef evthread_set_condition_callbacks
#undef evthread_set_id_callback
#undef evthread_set_lock_callbacks
#undef evthread_setup_global_lock_
#undef evbuffer_add
#undef evbuffer_add_buffer
#undef evbuffer_add_cb
#undef evbuffer_add_file
#undef evbuffer_add_printf
#undef evbuffer_add_reference
#undef evbuffer_add_vprintf
#undef evbuffer_cb_clear_flags
#undef evbuffer_cb_set_flags
#undef _evbuffer_chain_pin
#undef _evbuffer_chain_unpin
#undef evbuffer_clear_flags
#undef evbuffer_commit_space
#undef evbuffer_copyout
#undef _evbuffer_decref_and_unlock
#undef evbuffer_defer_callbacks
#undef evbuffer_drain
#undef evbuffer_enable_locking
#undef evbuffer_expand
#undef _evbuffer_expand_fast
#undef evbuffer_find
#undef evbuffer_free
#undef evbuffer_freeze
#undef evbuffer_get_contiguous_space
#undef evbuffer_get_length
#undef _evbuffer_incref
#undef _evbuffer_incref_and_lock
#undef evbuffer_invoke_callbacks
#undef evbuffer_lock
#undef evbuffer_new
#undef evbuffer_peek
#undef evbuffer_prepend
#undef evbuffer_prepend_buffer
#undef evbuffer_ptr_set
#undef evbuffer_pullup
#undef evbuffer_read
#undef evbuffer_readline
#undef evbuffer_readln
#undef _evbuffer_read_setup_vecs
#undef evbuffer_remove
#undef evbuffer_remove_buffer
#undef evbuffer_remove_cb
#undef evbuffer_remove_cb_entry
#undef evbuffer_reserve_space
#undef evbuffer_search
#undef evbuffer_search_eol
#undef evbuffer_search_range
#undef evbuffer_setcb
#undef evbuffer_set_flags
#undef evbuffer_set_parent
#undef _evbuffer_testing_use_linear_file_access
#undef _evbuffer_testing_use_mmap
#undef _evbuffer_testing_use_sendfile
#undef evbuffer_unfreeze
#undef evbuffer_unlock
#undef evbuffer_write
#undef evbuffer_write_atmost
#undef _bufferevent_add_event
#undef bufferevent_decref
#undef _bufferevent_decref_and_unlock
#undef _bufferevent_del_generic_timeout_cbs
#undef bufferevent_disable
#undef bufferevent_disable_hard
#undef bufferevent_enable
#undef bufferevent_enable_locking
#undef bufferevent_flush
#undef bufferevent_free
#undef _bufferevent_generic_adj_timeouts
#undef bufferevent_get_base
#undef bufferevent_get_enabled
#undef bufferevent_getfd
#undef bufferevent_get_input
#undef bufferevent_get_output
#undef bufferevent_get_underlying
#undef bufferevent_incref
#undef _bufferevent_incref_and_lock
#undef bufferevent_init_common
#undef _bufferevent_init_generic_timeout_cbs
#undef bufferevent_lock
#undef bufferevent_read
#undef bufferevent_read_buffer
#undef _bufferevent_run_eventcb
#undef _bufferevent_run_readcb
#undef _bufferevent_run_writecb
#undef bufferevent_setcb
#undef bufferevent_setfd
#undef bufferevent_settimeout
#undef bufferevent_set_timeouts
#undef bufferevent_setwatermark
#undef bufferevent_suspend_read
#undef bufferevent_suspend_write
#undef bufferevent_unlock
#undef bufferevent_unsuspend_read
#undef bufferevent_unsuspend_write
#undef bufferevent_write
#undef bufferevent_write_buffer
#undef bufferevent_base_set
#undef bufferevent_new
#undef bufferevent_ops_socket
#undef bufferevent_priority_set
#undef bufferevent_socket_connect
#undef bufferevent_socket_connect_hostname
#undef bufferevent_socket_get_dns_error
#undef bufferevent_socket_new
#undef bufferevent_filter_new
#undef bufferevent_ops_filter
#undef bufferevent_ops_pair
#undef bufferevent_pair_get_partner
#undef bufferevent_pair_new
#undef evconnlistener_disable
#undef evconnlistener_enable
#undef evconnlistener_free
#undef evconnlistener_get_base
#undef evconnlistener_get_fd
#undef evconnlistener_new
#undef evconnlistener_new_bind
#undef evconnlistener_set_cb
#undef evconnlistener_set_error_cb
#undef bufferevent_add_to_rate_limit_group
#undef _bufferevent_decrement_read_buckets
#undef bufferevent_decrement_read_limit
#undef _bufferevent_decrement_write_buckets
#undef bufferevent_decrement_write_limit
#undef bufferevent_get_max_to_read
#undef bufferevent_get_max_to_write
#undef bufferevent_get_read_limit
#undef _bufferevent_get_read_max
#undef bufferevent_get_write_limit
#undef _bufferevent_get_write_max
#undef bufferevent_rate_limit_group_decrement_read
#undef bufferevent_rate_limit_group_decrement_write
#undef bufferevent_rate_limit_group_free
#undef bufferevent_rate_limit_group_get_read_limit
#undef bufferevent_rate_limit_group_get_totals
#undef bufferevent_rate_limit_group_get_write_limit
#undef bufferevent_rate_limit_group_new
#undef bufferevent_rate_limit_group_reset_totals
#undef bufferevent_rate_limit_group_set_cfg
#undef bufferevent_rate_limit_group_set_min_share
#undef bufferevent_remove_from_rate_limit_group
#undef bufferevent_remove_from_rate_limit_group_internal
#undef bufferevent_set_rate_limit
#undef ev_token_bucket_cfg_free
#undef ev_token_bucket_cfg_new
#undef ev_token_bucket_get_tick
#undef ev_token_bucket_init
#undef ev_token_bucket_update
#undef event_changelist_add
#undef event_changelist_del
#undef event_changelist_freemem
#undef event_changelist_init
#undef event_changelist_remove_all
#undef evmap_check_integrity
#undef evmap_io_active
#undef evmap_io_add
#undef evmap_io_clear
#undef evmap_io_del
#undef evmap_io_get_fdinfo
#undef evmap_io_initmap
#undef evmap_signal_active
#undef evmap_signal_add
#undef evmap_signal_clear
#undef evmap_signal_del
#undef evmap_signal_initmap
#undef _event_debugx
#undef event_err
#undef event_errx
#undef event_msgx
#undef event_set_fatal_callback
#undef event_set_log_callback
#undef event_sock_err
#undef event_sock_warn
#undef event_warn
#undef event_warnx
#undef evutil_addrinfo_append
#undef evutil_adjust_hints_for_addrconfig
#undef evutil_ascii_strcasecmp
#undef evutil_ascii_strncasecmp
#undef evutil_closesocket
#undef evutil_ersatz_socketpair
#undef evutil_format_sockaddr_port
#undef evutil_freeaddrinfo
#undef evutil_gai_strerror
#undef evutil_getaddrinfo
#undef evutil_getaddrinfo_async
#undef evutil_getaddrinfo_common
#undef evutil_getenv
#undef evutil_hex_char_to_int
#undef evutil_inet_ntop
#undef evutil_inet_pton
#undef EVUTIL_ISALNUM
#undef EVUTIL_ISALPHA
#undef EVUTIL_ISDIGIT
#undef EVUTIL_ISLOWER
#undef EVUTIL_ISPRINT
#undef EVUTIL_ISSPACE
#undef EVUTIL_ISUPPER
#undef EVUTIL_ISXDIGIT
#undef evutil_make_listen_socket_reuseable
#undef evutil_make_socket_closeonexec
#undef evutil_make_socket_nonblocking
#undef evutil_new_addrinfo
#undef evutil_open_closeonexec
#undef evutil_parse_sockaddr_port
#undef evutil_read_file
#undef evutil_set_evdns_getaddrinfo_fn
#undef evutil_snprintf
#undef evutil_sockaddr_cmp
#undef evutil_sockaddr_is_loopback
#undef evutil_socket_connect
#undef evutil_socket_finished_connecting
#undef evutil_socketpair
#undef evutil_strtoll
#undef EVUTIL_TOLOWER
#undef EVUTIL_TOUPPER
#undef evutil_tv_to_msec
#undef evutil_vsnprintf
#undef _evutil_weakrand
#undef evutil_secure_rng_add_bytes
#undef evutil_secure_rng_get_bytes
#undef evutil_secure_rng_global_setup_locks_
#undef evutil_secure_rng_init
#undef _event_strlcpy
#undef selectops
#undef pollops
#undef epollops
#undef evsig_dealloc
#undef evsig_global_setup_locks_
#undef evsig_init
#undef _evsig_restore_handler
#undef evsig_set_base
#undef _evsig_set_handler
#undef evtag_consume
#undef evtag_decode_int
#undef evtag_decode_int64
#undef evtag_decode_tag
#undef evtag_encode_int
#undef evtag_encode_int64
#undef evtag_encode_tag
#undef evtag_init
#undef evtag_marshal
#undef evtag_marshal_buffer
#undef evtag_marshal_int
#undef evtag_marshal_int64
#undef evtag_marshal_string
#undef evtag_marshal_timeval
#undef evtag_payload_length
#undef evtag_peek
#undef evtag_peek_length
#undef evtag_unmarshal
#undef evtag_unmarshal_fixed
#undef evtag_unmarshal_header
#undef evtag_unmarshal_int
#undef evtag_unmarshal_int64
#undef evtag_unmarshal_string
#undef evtag_unmarshal_timeval
#undef evhttp_accept_socket
#undef evhttp_accept_socket_with_handle
#undef evhttp_add_header
#undef evhttp_add_server_alias
#undef evhttp_add_virtual_host
#undef evhttp_bind_listener
#undef evhttp_bind_socket
#undef evhttp_bind_socket_with_handle
#undef evhttp_bound_socket_get_fd
#undef evhttp_bound_socket_get_listener
#undef evhttp_cancel_request
#undef evhttp_clear_headers
#undef evhttp_connection_base_new
#undef evhttp_connection_connect
#undef evhttp_connection_fail
#undef evhttp_connection_free
#undef evhttp_connection_get_base
#undef evhttp_connection_get_bufferevent
#undef evhttp_connection_get_peer
#undef evhttp_connection_new
#undef evhttp_connection_reset
#undef evhttp_connection_set_base
#undef evhttp_connection_set_closecb
#undef evhttp_connection_set_local_address
#undef evhttp_connection_set_local_port
#undef evhttp_connection_set_max_body_size
#undef evhttp_connection_set_max_headers_size
#undef evhttp_connection_set_retries
#undef evhttp_connection_set_timeout
#undef evhttp_decode_uri
#undef evhttp_del_accept_socket
#undef evhttp_del_cb
#undef evhttp_encode_uri
#undef evhttp_find_header
#undef evhttp_free
#undef evhttp_htmlescape
#undef evhttp_make_request
#undef evhttp_new
#undef evhttp_parse_firstline
#undef evhttp_parse_headers
#undef evhttp_parse_query
#undef evhttp_parse_query_str
#undef evhttp_remove_header
#undef evhttp_remove_server_alias
#undef evhttp_remove_virtual_host
#undef evhttp_request_free
#undef evhttp_request_get_command
#undef evhttp_request_get_connection
#undef evhttp_request_get_evhttp_uri
#undef evhttp_request_get_host
#undef evhttp_request_get_input_buffer
#undef evhttp_request_get_input_headers
#undef evhttp_request_get_output_buffer
#undef evhttp_request_get_output_headers
#undef evhttp_request_get_response_code
#undef evhttp_request_get_uri
#undef evhttp_request_is_owned
#undef evhttp_request_new
#undef evhttp_request_own
#undef evhttp_request_set_chunked_cb
#undef evhttp_response_code
#undef evhttp_send_error
#undef evhttp_send_page
#undef evhttp_send_reply
#undef evhttp_send_reply_chunk
#undef evhttp_send_reply_end
#undef evhttp_send_reply_start
#undef evhttp_set_allowed_methods
#undef evhttp_set_cb
#undef evhttp_set_gencb
#undef evhttp_set_max_body_size
#undef evhttp_set_max_headers_size
#undef evhttp_set_timeout
#undef evhttp_start
#undef evhttp_start_read
#undef evhttp_uridecode
#undef evhttp_uriencode
#undef evhttp_uri_free
#undef evhttp_uri_get_fragment
#undef evhttp_uri_get_host
#undef evhttp_uri_get_path
#undef evhttp_uri_get_port
#undef evhttp_uri_get_query
#undef evhttp_uri_get_scheme
#undef evhttp_uri_get_userinfo
#undef evhttp_uri_join
#undef evhttp_uri_new
#undef evhttp_uri_parse
#undef evhttp_uri_parse_with_flags
#undef evhttp_uri_set_flags
#undef evhttp_uri_set_fragment
#undef evhttp_uri_set_host
#undef evhttp_uri_set_path
#undef evhttp_uri_set_port
#undef evhttp_uri_set_query
#undef evhttp_uri_set_scheme
#undef evhttp_uri_set_userinfo
#undef evdns_add_server_port
#undef evdns_add_server_port_with_base
#undef evdns_base_clear_nameservers_and_suspend
#undef evdns_base_count_nameservers
#undef evdns_base_free
#undef evdns_base_load_hosts
#undef evdns_base_nameserver_add
#undef evdns_base_nameserver_ip_add
#undef evdns_base_nameserver_sockaddr_add
#undef evdns_base_new
#undef evdns_base_resolv_conf_parse
#undef evdns_base_resolve_ipv4
#undef evdns_base_resolve_ipv6
#undef evdns_base_resolve_reverse
#undef evdns_base_resolve_reverse_ipv6
#undef evdns_base_resume
#undef evdns_base_search_add
#undef evdns_base_search_clear
#undef evdns_base_search_ndots_set
#undef evdns_base_set_option
#undef evdns_cancel_request
#undef evdns_clear_nameservers_and_suspend
#undef evdns_close_server_port
#undef evdns_count_nameservers
#undef evdns_err_to_string
#undef evdns_getaddrinfo
#undef evdns_getaddrinfo_cancel
#undef evdns_get_global_base
#undef evdns_init
#undef evdns_nameserver_add
#undef evdns_nameserver_ip_add
#undef evdns_resolv_conf_parse
#undef evdns_resolve_ipv4
#undef evdns_resolve_ipv6
#undef evdns_resolve_reverse
#undef evdns_resolve_reverse_ipv6
#undef evdns_resume
#undef evdns_search_add
#undef evdns_search_clear
#undef evdns_search_ndots_set
#undef evdns_server_request_add_aaaa_reply
#undef evdns_server_request_add_a_reply
#undef evdns_server_request_add_cname_reply
#undef evdns_server_request_add_ptr_reply
#undef evdns_server_request_add_reply
#undef evdns_server_request_drop
#undef evdns_server_request_get_requesting_addr
#undef evdns_server_request_respond
#undef evdns_server_request_set_flags
#undef evdns_set_log_fn
#undef evdns_set_option
#undef evdns_set_random_bytes_fn
#undef evdns_set_transaction_id_fn
#undef evdns_shutdown
#undef evrpc_add_hook
#undef evrpc_free
#undef evrpc_get_reply
#undef evrpc_get_request
#undef evrpc_hook_add_meta
#undef evrpc_hook_find_meta
#undef evrpc_hook_get_connection
#undef evrpc_init
#undef evrpc_make_request
#undef evrpc_make_request_ctx
#undef evrpc_pool_add_connection
#undef evrpc_pool_free
#undef evrpc_pool_new
#undef evrpc_pool_remove_connection
#undef evrpc_pool_set_timeout
#undef evrpc_register_generic
#undef evrpc_register_rpc
#undef evrpc_remove_hook
#undef evrpc_reqstate_free
#undef evrpc_request_done
#undef evrpc_request_get_pool
#undef evrpc_request_set_cb
#undef evrpc_request_set_pool
#undef evrpc_resume_request
#undef evrpc_send_request_generic
#undef evrpc_unregister_rpc
